<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS><TS version="2.0" language="ru_RU" sourcelanguage="">
<context>
    <name>Plugin</name>
    <message>
        <location filename="qgis2mobile.py" line="256"/>
        <source>No device to import</source>
        <translation>Устройство для импорта не найдено</translation>
    </message>
    <message>
        <location filename="qgis2mobile.py" line="227"/>
        <source>Settings</source>
        <translation>Настройки</translation>
    </message>
    <message>
        <location filename="qgis2mobile.py" line="341"/>
        <source>qgis2mobile</source>
        <translation></translation>
    </message>
    <message>
        <location filename="qgis2mobile.py" line="248"/>
        <source>Import layer to device</source>
        <translation>Импортировать слой на устройство</translation>
    </message>
    <message>
        <location filename="qgis2mobile.py" line="250"/>
        <source>The device is connected</source>
        <translation>Устройство подключено</translation>
    </message>
    <message>
        <location filename="qgis2mobile.py" line="259"/>
        <source>The device is disconnected</source>
        <translation>Устройство отключено</translation>
    </message>
    <message>
        <location filename="qgis2mobile.py" line="286"/>
        <source>Plugin is not configured</source>
        <translation>Плагин не сконфигурирован</translation>
    </message>
    <message>
        <location filename="qgis2mobile.py" line="293"/>
        <source>Layer is not selected</source>
        <translation>Слой не выбран</translation>
    </message>
    <message>
        <location filename="qgis2mobile.py" line="299"/>
        <source>Selected layer is not a vector</source>
        <translation>Выбирите векторный слой</translation>
    </message>
    <message>
        <location filename="qgis2mobile.py" line="329"/>
        <source>Import ERROR: QgsVectorFileWriter ERROR</source>
        <translation>Ошибка при импорте данных: QgsVectorFileWriter ERROR</translation>
    </message>
    <message>
        <location filename="qgis2mobile.py" line="334"/>
        <source>The import was successful!</source>
        <translation>Ипорт данных прошел успешно!</translation>
    </message>
    <message>
        <location filename="qgis2mobile.py" line="349"/>
        <source>Import ERROR</source>
        <translation type="obsolete">Ошибка при импорте данных</translation>
    </message>
</context>
<context>
    <name>SettingsDialog</name>
    <message>
        <location filename="qgis2mobile.py" line="98"/>
        <source>Select directory</source>
        <translation>Выбирите директорию</translation>
    </message>
    <message>
        <location filename="qgis2mobile.py" line="124"/>
        <source>Removable disk</source>
        <translation>Съемный диск</translation>
    </message>
    <message>
        <location filename="qgis2mobile.py" line="129"/>
        <source>curent</source>
        <translation>текущий</translation>
    </message>
</context>
<context>
    <name>qgis2mobileSettings</name>
    <message>
        <location filename="qgis2mobile_settings.ui" line="14"/>
        <source>qgis2mobile settings</source>
        <translation>Настройки qgis2mobile </translation>
    </message>
    <message>
        <location filename="qgis2mobile_settings.ui" line="33"/>
        <source>Browse...</source>
        <translation>Обзор...</translation>
    </message>
    <message>
        <location filename="qgis2mobile_settings.ui" line="42"/>
        <source>Import to:</source>
        <translation>Ипортировать в:</translation>
    </message>
    <message>
        <location filename="qgis2mobile_settings.ui" line="55"/>
        <source>Device:</source>
        <translation>Устройство:</translation>
    </message>
</context>
</TS>
